### ISSUE TITLE
Melhoria no cargo UX

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#117]
Atualmente temos apenas o cargo "UX".
Acho que seria interessante estruturar melhor os cargos de UX, pois existem diversas áreas dentro de UX.
Um exemplo que temos é o cargo "Data" que se tornou uma categoria, digamos assim, pois além dele temos "Data Analyst", "Data Engineer" e "Data Scientist"

**Comment by dansenpir** [comment]
@thainarawulfert consegue me ajudar nisso?

**Comment by thainarawulfert** [comment]
Oi Dan, consigo ajudar sim! qual seria a melhor forma da gente organizar isso? criamos uma lista de cargos e suas ramificações para assim a gente ter um cargo direcionado e não global?

**Comment by dansenpir** [comment]
@thainarawulfert o padrão que adotei nos demais cargos foi ter uma área e suas especialidades.
Exemplos:
Developer é uma área, e backend, frontend e mobile são especialidades.
Product é uma área, e business analyst, product manager e product owner são especialidades.

Precisamos de algo assim para a área de UX.
Uma especialidade que conheço é a UX Writer, mas teria que mapear as outras para ficar tudo padronizado.

**Comment by thainarawulfert** [comment]
Na área de UX nós temos :
UX Research
UX Writing
UX Design
e temos que levar em conta que as vezes é necessário apenas um UI Design 

Não sei se isso pode contribuir

**Comment by dansenpir** [comment]
@thainarawulfert, podemos seguir com a criação desses cargos.

Com os cargos criados, seria necessário:
- Adicionar essas opções de registro usando o SlashBot no canal 🖊┃ux;
- Ajustar as permissões do servidor, trocando o que antes era liberado pelo cargo "UX" pelos 4 cargos novos criados.

Consegue atuar nisso, @thainarawulfert?

**Comment by thainarawulfert** [comment]
Bom dia, tudo resolvido e configurado! Caso haja necessidade de outra atividade estou com a semana disponível

**Comment by dansenpir** [comment]
@thainarawulfert, validando aqui eu encontrei configurações que ficaram faltando, segue os canais que não estão com as permissões configuradas:

- ❓┃dúvidas-servidor
- 💡┃sugestões-servidor
- 🚨┃denúncias
-  📝┃apresente-se

Consegue ajustar?

**Comment by thainarawulfert** [comment]
@dansenpir Bom dia Dan, agora sim está tudo certo! Falta de atenção da minha parte porém tudo dentro dos conformes

**Comment by dansenpir** [comment]
Tarefa finalizada.
