### ISSUE TITLE
Descubra Ilhabela

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#119]
**Descrição enviada pelo formulário:**
"Peguei como base minha cidade por ser bem turistica e tive a ideia de desenvolver um "Guia Turistico". Não vou explicar oque vai ter em cada rota pra não estrapolar, porém, resumindo estou pensando nas seguintes rotas: Rota Histórica, Rota Gastronômica, Rota Natural, Rota Aventura, Rota Cultural, Rota de Compras, Rota de Hospedagem. Um adiocional seria o usuario poder criar uma lista de pontos turisticos ou relacionados que ela mais gostou e poderá adioconar , remover e listar se já foi ou não. Seria interessante Listar pontos turísticos da cidade;
Permitir que os usuários vejam informações detalhadas sobre cada ponto turístico;
Permitir que os usuários obtenham rotas e direções para cada ponto turístico usando uma API de mapa;
Permitir que os usuários classifiquem e avaliem cada ponto turístico;
Permitir que os usuários adicionem novos pontos turísticos ao sistema (com moderação de conteúdo);
Permitir que os usuários deixem comentários e sugestões sobre cada ponto turístico.

em resumo é isto, só clariar as ideias e modelar da melhor maneira e priozar a UI/UX"

**Founder**:
Usuário Discord: Pauloo#2189

**A fazer**
- Conceder o cargo "Lab | Responsável Recrutamento" ao Founder;
- Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- Se colocar à disposição para dúvidas;
- Revisar o Pull Request quando enviado, checando se está em conformes com o que pedimos na Wiki;
- Lançar o projeto.

**Comment by dansenpir** [comment]
@iltrd, consegue lançar esse projeto?
Estou à disposição, caso tenha dúvidas.

**Comment by iltrd** [comment]
@dansenpir Consigo! Qualquer dúvida entro em contato com você.

**Comment by iltrd** [comment]
Entrei em contato com o Founder dia 04/05, informei que o cargo já foi concedido e que ele poderia iniciar o recrutamento. O recrutamento já foi iniciado, estou acompanhando pelo post e verificando se o founder tem alguma dúvida a respeito.

**Comment by iltrd** [comment]
Relato da task: 

 - o Founder precisou criar uma postagem nova para o recrutamento, pois a primeira foi apagada devido à menção de muitas pessoas de uma só vez e ele não possuía a verificação de duas etapas. A plataforma identificou como uma possível invasão. Com isso solucionado, ele solicitou ajuda do staff para a criação da organização e do PR para validação. 

11/05 - PR validado, canal e cargo criados. Founder e Membros com cargos concedidos.
