### ISSUE TITLE
[Sugestão] "Roadmap" para preparar membros para projetos

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#120]
![Image](https://user-images.githubusercontent.com/22007659/236282223-4895d542-7832-405d-98cd-61d8b4488170.png)
![Image](https://user-images.githubusercontent.com/22007659/236282312-887d0998-8c81-47c2-b794-20a315e93877.png)
![Image](https://user-images.githubusercontent.com/22007659/236282383-5a830158-f6e5-4d8d-8766-4c98bacbfe92.png)

Link da sugestão: https://discord.com/channels/759176734460346423/1092816503461646416

**A fazer**
- Análise de viabilidade de implementação da sugestão;
- Definição de formato (um repositório no GitHub seria uma solução?);
- Se viável, implementar, caso contrário descartar e deixar a justificativa no post da sugestão.

**Comment by dansenpir** [comment]
@AlecLimaDev, conforme falamos, conto contigo com isso.

**Comment by AlecLimaDev** [comment]
Boa tarde.

Achei a ideia dele boa, mas acredito que o que ele solicita no momento foge um pouco da ideia da SouJunior. De qualquer forma, considerei colocar essa sugestão para ser "validada" e discutida para possível implementação futura.

Uma das coisas que me fez considerar essa ideia para "validação" foi o fato de termos que dar suporte ao implementá-la. E, pelo que entendi resumidamente, o que ele solicita pode ser facilmente encontrado em pesquisas, não sendo tão importante ser aplicado neste momento.

Penso que é uma boa ideia aplicá-la, mas como precisamos dar suporte, acredito que devemos discutir os prós e contras e prioridades neste momento.

Estou aberto a conversar sobre isso, então podem me enviar mensagem no Discord ou Linkedin se quiserem.
