### ISSUE TITLE
Melhoria no cargo Product Manager

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#121]
Atualmente temos apenas o cargo "Product Manager".
Acho que seria interessante estruturar melhor os cargos de Product Manager, pois existem diversas áreas dentro de Product Manager.
Um exemplo que temos é o cargo "Data" que se tornou uma categoria, digamos assim, pois além dele temos "Data Analyst", "Data Engineer" e "Data Scientist"

**Comment by dansenpir** [comment]
@AlynneMartins consegue me ajudar a ramificar o cargo de Product Manager?

**Comment by dansenpir** [comment]
Tenho alguns pontos, @AlynneMartins:

- Se a área seria "Product Manager", teríamos uma área "Product Manager" dentro? Não fica estranho? Ou sugere, por exemplo, renomear a área para "Product" e dentro dela termos "Product Manager"?
- Entendo que no contexto do servidor, todos sejam APM, praticamente, então faz sentido usarmos ou devemos focar em BA, PO e PM, que seria lido como o que o membro almeja se tornar?

**Comment by AlynneMartins** [comment]
Isso @dansenpir, a área é **Produto**!

Realmente, todos são APM. Podemos focar apenas em: BA, PO e  PM.

**Comment by dansenpir** [comment]
@AlynneMartins, criei os cargos e já os inclui no registro do servidor.
Obrigado pela ajuda!
