### ISSUE TITLE
Melhoria no cargo Agile

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#122]
Atualmente temos apenas o cargo "Agile".
Acho que seria interessante estruturar melhor os cargos de Agile pois existem diversas áreas dentro de Agile.
Um exemplo que temos é o cargo "Data" que se tornou uma categoria, digamos assim, pois além dele temos "Data Analyst", "Data Engineer" e "Data Scientist"

**Comment by dansenpir** [comment]
@BeatrizzRibeiro @iltrd 
Conseguem me ajudar nisso?
Basicamente Agile seria a área e precisamos adicionar as suas especialidades em formato de cargos no servidor.

**Comment by iltrd** [comment]
@dansenpir pelo que eu entendo existem 4 cargos dentro de agile sendo eles:

> **Scrum Master** garante que todos entendem a teoria, as práticas e valores do Scrum, apoia Product Owner na organização do Backlog do Produto para maximar valor, facilita os eventos do Scrum, resolve impedimentos e apoia a organização na adoção do Scrum.
**Agile Master** tem o mesmo papel do Scrum Master, mas pode também aplicar práticas além do Scrum como o Método Kanban e Extreme programming (XP), entender de escalabidade SAFE e Nexus (por exemplo) e métricas ágeis.
**Agile Coach** realiza suporte a outros Scrum Masters/Agile Masters, Product Owners e gestores da organização, apoia os times na execução dos seus papéis, realiza workshops, treina os times, dissemina a agilidade nível organizacional, atua como coach em agilidade, busca alcançar metas, elabora/usa indicadores e métricas ágeis.
 **Agilista** é a pessoa que trabalha com agilidade independente do método usado, pode atuar tanto como Agile Coach ou Agile Master.

**Comment by dansenpir** [comment]
@iltrd, talvez o cargo "Agilista" seja dispensável, pois como o intuito é aprendizado, melhor focar em alguma especialidade.
E como já é permitido optar por duas especialidades, acho que é o suficiente, então penso em focar nos outros 3.
Faz sentido?

**Comment by iltrd** [comment]
@dansenpir Faz sentido! Farei isso.

**Comment by dansenpir** [comment]
@iltrd, podemos seguir com a criação desses cargos.

Com os cargos criados, seria necessário:

Adicionar essas opções de registro usando o SlashBot no canal 🖊┃agile;
Ajustar as permissões do servidor, trocando o que antes era liberado pelo cargo "Agile" pelos 3 cargos novos criados.
Consegue atuar nisso, @iltrd?

**Comment by dansenpir** [comment]
![Image](https://github.com/SouJunior/soujunior-lab/assets/22007659/b6fe140a-a0b3-4a8e-8abb-2e187e5568e5)

**Comment by dansenpir** [comment]
![Image](https://github.com/SouJunior/soujunior-lab/assets/22007659/88df5ed2-f8bf-4f54-9a09-7dd415e7f2b5)

**Comment by dansenpir** [comment]
@iltrd, validando aqui percebi que faltou ajustar as permissões nos fóruns dos prints acima e também nas categorias "COMMUNITY" e "COMMUNITY | VOZ".

Consegue resolver?

**Comment by iltrd** [comment]
Ajuste nos fóruns

- [ ] dúvidas-servidor
- [ ] sugestões-servidor
- [ ] denúncias
- [ ] depósito-de-ideias
- [ ] evolução-de-ideias
- [ ] recrutamento
- [ ] Community
- [ ] Community | voz

**Comment by iltrd** [comment]
@dansenpir Ajustes realizados

**Comment by dansenpir** [comment]
Validado.
