### ISSUE TITLE
Estrutura de Cargos no servidor

### ISSUE THREAD

**Issue by wouerner** [SouJunior/soujunior-lab#123]
Preciso que me apresentem a estrutura de cargos no servidor.

Eu quero validar os que existem.

**Comment by dansenpir** [comment]
- CM
- Moderator
- Staff
- Server Booster
- Parceria
- Colaboradores
- ...cargos dos projetos
- Mídia (cargo legado)
- Esquema de área e especialidades, como por exemplo: área: Developer, especialidades: backend, frontend e mobile, ou então área: product, especialidades: business analyst, product manager e product owner
- Lab (antigo cargo Community).

**Comment by dansenpir** [comment]
@wouerner, estou movendo este card para done.
