### ISSUE TITLE
Boas práticas ao iniciar um projeto

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#125]
**Descrição**:
Necessário criar uma documentação com sugestões de boas práticas ao iniciar um projeto na comunidade SouJunior Lab.

**Motivação**:
Guiar os iniciantes em um caminho sem tanta dificuldade ao criar projetos.

**O que deve ser feito nessa task**

- [x] Discussão aqui nos comentários sobre o que podemos considerar boas práticas;
- [x] Validação das boas práticas;
- [x] Elaboração de uma página na Wiki com o compilado dessas boas práticas;
- [ ] Validação da página Wiki.

**Comment by dansenpir** [comment]
@AlynneMartins @BeatrizzRibeiro 
Como vocês possuem um background de agilidade, produto e ux, acredito que conseguirão trazer bons insights nessa task.
Conseguem ajudar?

**Comment by AlynneMartins** [comment]
Na verdade ainda não parei para avaliar direitinho a demanda, @dansenpir . Nesse fds já dou prosseguimento!

**Comment by AlynneMartins** [comment]
Boas práticas para novos projetos:

- Organize a sua ideia de projeto. Se necessário, peça ajuda para refiná-la no fórum #evoluçãodeideia.
- Preencha o formulário do SouJunior Lab de forma detalhada, assim você se torna o founder do projeto e pode começar as atividades
- Projeto validado, você precisa de um repositório no GitHub e este precisa possuir: o tópico "soujunior-lab" e uma licença open source
- Agora poderá começar o recrutamento da sua equipe no canal #recrutamento do Discord
- Lembre-se que para um projeto seguir bem é necessário que tenha pelo menos: 2 PMs, 2 Agilistas e 2 UXs no seu time
- Leve em consideração os horários disponíveis dos possíveis membros da equipe, para que não haja desencontros e possíveis entraves
- Avalie também se o futuro membro não está em 2 projetos, só é possível participar de até 2 projetos simultaneamente
- Conseguiu recrutar todos os membros? Faça um fork e Pull Request e você receberá um canal de texto no Discord da SouJunior para comunicação com o seu time
- Liste todos os membros recrutados e marque o staff para que todos sejam adicionados ao canal e possam fazer parte das atividades
- Prontinho. Façam o projeto acontecer!


Não sei se era exatamente isso que você queria, @dansenpir. Caso não, me oriente para que eu possa refazê-lo.
E caso esteja faltando algo, me pontue também. Obrigada!

**Comment by dansenpir** [comment]
@AlynneMartins, nada me vem a mente.
Acho que ficou bom dessa forma, faltando apenas adaptar isso para uma página Wiki.

**Comment by AlynneMartins** [comment]
Beleza, @dansenpir. Irei fazer essa adaptação!

**Comment by dansenpir** [comment]
@iltrd, consegue checar com a @AlynneMartins se já foi produzido e encerrar essa task?

**Comment by iltrd** [comment]
@dansenpir Consigo, segunda-feira verifico isso.

**Comment by iltrd** [comment]
@dansenpir Com os passos feito pela Alynne, segui com a elaboração da página na wiki https://github.com/SouJunior-Lab/project-list/wiki/Boas-pr%C3%A1ticas-ao-iniciar-um-projeto

**Comment by iltrd** [comment]
@dansenpir Pensei em detalhar um pouco as dicas, o que acha?

**Comment by dansenpir** [comment]
Ficou bom, @iltrd.
Apenas ajustei o título e inseri o novo banner do Labs.
