### ISSUE TITLE
Criação dos cargos de "mentores especialistas"

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#130]
**Descrição**:
Criação dos cargos das áreas específicas para cada mentor.

**Motivação**:
Melhor direcionamento dos mentores no servidor.

**O que deve ser feito nessa task:**
- [x] Criação do cargo "Mentor Agile";
- [x] Criação do cargo "Mentor Data";
- [x] Criação do cargo "Mentor Developer";
- [x] Criação do cargo "Mentor DevOps";
- [x] Criação do cargo "Mentor Product";
- [x] Criação do cargo "Mentor Quality";
- [x] Criação do cargo "Mentor Tech Recruiter";
- [x] Criação do cargo "Mentor UX";
- [x] Adequação dos novos cargos no fluxo de registro do servidor.

**Comment by dansenpir** [comment]
@iltrd consegue assumir isso?

**Comment by iltrd** [comment]
@dansenpir Consigo sim!

**Comment by thainarawulfert** [comment]
@iltrd se precisar de ajuda, estou à disposição!

**Comment by dansenpir** [comment]
@iltrd @thainarawulfert 
Acabei decidindo trocar o SlashBot pelo ProBot para registro no servidor e com isso acabei fazendo essa task, pois precisava dos cargos.
