### ISSUE TITLE
Fóruns de Mentorias

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#131]
**Descrição**:
Quebra do fórum "mentoria" em fóruns específicos.

**Motivação**:
Melhor direcionamento das mentorias no servidor.

**O que deve ser feito nessa task:**
- [x] Aguardar o término da task #130;
- [x] Criação da categoria "Mentoria", seguindo o padrão de nomenclatura das demais categorias;
- [x] Restringir o acesso a categoria "Mentoria" aos cargos "Junior" e "Mentor";
- [x] Criação do fórum "mentoria-agile";
- [x] Criação do fórum "mentoria-data";
- [x] Criação do fórum "mentoria-developer";
- [x] Criação do fórum "mentoria-devops";
- [x] Criação do fórum "mentoria-product";
- [x] Criação do fórum "mentoria-quality";
- [x] Criação do fórum "mentoria-techrecruiter";
- [x] Criação do fórum "mentoria-ux";
- [x] Todos os fóruns criados devem ser restritos aos cargos de especialidades, como por exemplo o fórum "mentoria-agile" é restrito aos cargos "Mentor Agile", "Agile Coach", "Agile Master" e "Scrum Master".
- [x] Criação de tags relacionadas a cada um dos fóruns criados;
- [x] Restringir a criação de posts apenas se possuir tags;
- [x] Criar um post em cada um dos fóruns com o título "[NOME_DO_FÓRUM] | Como usar este fórum" contendo as instruções de uso do fórum;
- [x] Quando tudo for finalizado, barrar a criação de novos posts no fórum "mentoria" (o que estamos substituindo);
- [x] Quando tudo for finalizado, trancar todos os posts em desuso do fórum "mentoria";
- [x] Quando tudo for finalizado, criar um comunicado informando dos novos posts e informando que o histórico do fórum "mentoria" será mantido por mais 7 dias, porém que não será possível criar novos posts, então a comunicação deve ser movida para os novos fóruns.

**Comment by dansenpir** [comment]
@thainarawulfert, a task #130 já foi finalizada, então pode atuar aqui quando conseguir, por favor.

**Comment by dansenpir** [comment]
@cplxx, necessário ajustar as tags.
Consegue atuar nisso, por favor?

**Comment by dansenpir** [comment]
@cplxx, como estamos nessa task?

**Comment by cplxx** [comment]
@dansenpir finalizada

**Comment by cplxx** [comment]
@dansenpir finalizada
