### ISSUE TITLE
Canal para divulgação de pesquisas UX

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#136]
**Descrição**:
Criação de um canal de texto para divulgação de pesquisas dos projetos.

**Motivação**:
Espaço direcionado para publicação de pesquisas no servidor.

**O que deve ser feito nessa task:**
- [x] Criar o canal "pesquisas" dentro da categoria "╭‒‒‒⥽ Projetos";
- [x] Restringir o envio de mensagem para o cargo "Projeto | Membro";
- [x] Os cargos a seguir e somente eles, podem visualizar o conteúdo do canal:
- - [x] Agile Coach
- - [x] Agile Master
- - [x] Scrum Master
- - [x] Data Analyst
- - [x] Data Engineer
- - [x] Data Scientist
- - [x] BackEnd
- - [x] FrontEnd
- - [x] Mobile
- - [x] DevSecOps
- - [x] IaC
- - [x] SRE
- - [x] Business Analyst
- - [x] Product Manager
- - [x] Product Owner
- - [x] Quality Assurance
- - [x] Tech Recruiter
- - [x] UX Design
- - [x] UX Research
- - [x] UX Writing
- - [x] UI Design
- [ ] Fazer um comunicado avisando a comunidade, em especial os membros de projetos, dessa nova possibilidade.

**Comment by dansenpir** [comment]
@thainarawulfert, consegue atuar nisso?

**Comment by thainarawulfert** [comment]
@dansenpir Consigo sim, assim que possível começo a produção

**Comment by dansenpir** [comment]
@thainarawulfert precisa de ajuda?

**Comment by dansenpir** [comment]
task finalizada.
