### ISSUE TITLE
Mentor Cycle

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#137]
**Descrição enviada pelo formulário de registro de projeto**:
"Ajudar pessoas a conseguir mentorias na área de T.I."

**Founder**:
Usuário Discord: Leonardo Balsalobre#9871

**A fazer**

- [x] Conceder o cargo "Lab | Responsável Recrutamento" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Revisar o Pull Request quando enviado, checando se está em conformes com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Lab no Discord, configurar as permissões dos cargos conforme os demais cargos de projetos;
- [x] Criar o canal do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos.

**Observação:**
Este projeto, em específico, deve iniciar no Stage 02, pois está para lançar seu MVP essa semana e escolheu unir forças com o SouJunior Lab.
Porém, valide junto ao Founder se o projeto cumpre todos os requisitos necessários dos Stages anteriores.
Qualquer dúvida, me procure.

**Comment by iltrd** [comment]
Vi que o founder não está no servidor, tentei contato via mensagem direta, mas aparece que ele só recebe mensagem direta de amigos

**Comment by dansenpir** [comment]
@iltrd, validado.
Uma observação é que só deve ser criado o cargo e canal do projeto quando o Pull Request for aprovado e mergeado, após validado todos os pontos da Wiki.
Caso você não esteja com permissão para fazer merge dos PRs, me avise.
