### ISSUE TITLE
Onboarding Tech Recruiters Voluntários

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#138]
**Descrição**:
Onboarding dos Tech Recruiters voluntários que conseguimos recrutar.

**Motivação**:
Apresentação da equipe ao Wouerner e apresentação de suas atividades.

**O que deve ser feito nessa task:**
- [ ] Agendamento de reunião com horário compatível com a participação de todos ou da maioria;
- [ ] Realização do onboarding;
- [ ] Definição da plataforma a ser utilizada para registro de atividades;
- [ ] Elaboração do formulário a ser disponibilizado aos Founders para atuação posterior dos Tech Recruiters com a supervisão da Mari.

**Comment by dansenpir** [comment]
@wouerner @marimoraes21 

Como estamos em relação a isso?
Consigo ajudar em algo?

**Comment by marimoraes21** [comment]
Dan,
já alinhamos, apenas para formalizar e eliminar esta pendência.
- Alinhei com o Brandão sobre o papel dos recrutadores na comunidade
- O time conta com 1 mentora e 3 tech recruiters
- Informaremos aos founders sobre a possibilidade de solicitar ao um TR que faça o recrutamento das vagas em aberto
- Será criado um fórum exclusivo para founders e recruiters se comunicarem
- Os encontros da squad será as quintas, 20h

Se houver mais alguma pendência desse tópico, por favor me sinalize.

**Comment by dansenpir** [comment]
Fluxo finalizado.
