### ISSUE TITLE
Exclusão dos canais de projetos não utilizados

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#142]
**Descrição**:
Com a conclusão das tasks #140 e #141, resta excluir os canais dos projetos que não são utilizados.

**Motivação**:
Tornar opcional o uso de canais dentro do servidor para chat, uma vez que a comunicação com o SouJunior Lab passa a ser pelos canais de Weekly.

**O que deve ser feito nessa task:**
- [x] Criar um comunicado no canal 📣┃avisos-projetos informando sobre a mudança e direcionando para a Wiki;
- [x] Deixar claro que a partir do dia **16/06** o uso das Weeklys passa a ser o novo padrão de comunicação com o SouJunior Lab, mas que já pode começar a ser utilizado;
- [x] Informar que os canais de chat dos projetos ainda podem ser utilizados, porém passam a ser opcionais;
- [x] Abordar todos os Founders do projeto, reforçando o comunicado e estipulando que caso não demonstrem interesse em manter o canal de chat do projeto até o dia **14/06**, este será excluído.

**Comment by dansenpir** [comment]
@iltrd, as tasks #140 e #141 foram concluídas, então já é possível atuar nessa task.

**Comment by iltrd** [comment]
Projetos 

- [ ] Wizer
- [ ] Video4Me
- [ ] Site Projetos Ativos
- [ ] Pet Journal
- [ ] Controle de Corrida
- [ ] Findy
- [ ] Cartão Fidelidade Digital
- [ ] Animania
- [ ] Minnemi
- [ ] Anota Aí
- [ ] LoryBly
- [ ] Connecttattoo
- [ ] Routinely
- [ ] TerceiroGestor
- [ ] Care4You
- [ ] Bora Rachar
- [ ] Spotistas
- [ ] TechRate
- [ ] Onde é o rolê
- [ ] Quest Finder
- [ ] CollectEasy
- [ ] Descubra Ilhabela
- [ ] Sistema de Gerenciamento de Projetos
- [ ] Mentor Cycle

**Comment by iltrd** [comment]
Após o período estipulado no primeiro comunicado, e diante da falta de comunicação dos founders dos projetos, procedi com a exclusão dos seguintes canais:

- Site dos Projetos Ativos
- Findy
- Care4You
- Onde é o rolê

**Comment by dansenpir** [comment]
@iltrd 
Perfeito.
Task finalizada.
