### ISSUE TITLE
MenuExpresso

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#143]
**Descrição enviada pelo formulário de registro de projeto**:
"O projeto se trata de um cardápio digital para pequenos e médios estabelecimentos. A ideia é facilitar o atendimento entre o consumidor e o estabelecimento através de pedidos utilizando o whatszapp."

**Founder**:
Usuário Discord: CPLX#3061

**A fazer**

- [x] Conceder o cargo "⚒┃Membro" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Revisar o Pull Request quando enviado, checando se está em conformes com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Lab no Discord, configurar as permissões dos cargos conforme os demais cargos de projetos;
- [x] Criar o canal do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos.

**Comment by dansenpir** [comment]
@jonasemanuel essa task já foi iniciada?
Precisa de ajuda?

**Comment by salviotonon** [comment]
@dansenpir projeto em etapa de recrutamento de novos membros.

**Comment by dansenpir** [comment]
@salviotonon 
Os canais de Weekly e de comunicação (caso tenha sido optado), foram criados **após** o recrutamento do mínimo de membros de cada área?

**Comment by salviotonon** [comment]
@dansenpir 

não, foram abertos durante o processo de comunicação com o founder. atualmente o projeto esta em fase de recrutamento,menuExpresso optou por criar o chat do projeto

**Comment by dansenpir** [comment]
Fluxo finalizado.
