### ISSUE TITLE
Warmy

### ISSUE THREAD

**Issue by dansenpir** [SouJunior/soujunior-lab#144]
**Descrição enviada pelo formulário de registro de projeto**:
"O objetivo principal da aplicação é facilitar a localização de doadores de agasalhos, permitindo que as entidades competentes possam ir até eles. A aplicação terá funcionalidades como tirar fotos das peças, fornecer informações objetivas sobre as mesmas, exibir um mapa com indicadores de doadores e oferecer acessos separados para doadores e entidades.

A aplicação será desenvolvida utilizando React.js e React Native, abrangendo web, iOS e Android. Serão considerados requisitos de segurança, como utilizar o número de telefone para login e restringir o acesso à localização exata apenas para as entidades.

A localização dos usuários será identificada através de uma API de geolocalização open source, mas a API do Google também pode ser considerada, desde que seja uma solução sem fins lucrativos.

Ao encontrar pontos de coleta de agasalhos, os usuários poderão visualizar informações relevantes, como a quantidade de doações feitas na região, o total de doações feitas por eles mesmos, balões indicando doadores próximos e pontos de coleta. Também será possível filtrar os pontos de coleta por critérios como proximidade, tipo de agasalho e instituição beneficiada.

Apenas as entidades/instituições poderão cadastrar novos pontos de coleta, e para isso, serão solicitadas informações como CNPJ e documentação que comprove a seriedade da instituição. Caso não haja documentação, será possível solicitar uma validação manual.

A validação das informações fornecidas pelos usuários ao cadastrar um ponto de coleta será feita através do acesso a dados do governo, verificação de documentos e investigação da veracidade e comprometimento da equipe, quando não houver validação manual.

Haverá um sistema de notificações para alertar os usuários sobre novos pontos de coleta e campanhas de doação. Além disso, os usuários poderão fazer doações diretamente através do aplicativo, com a possibilidade de utilização de pix como método de pagamento.

O controle e a prestação de contas das doações recebidas serão feitos preferencialmente através de integração do pix, para que as doações sejam direcionadas diretamente para a conta da entidade validada.

Será necessário integrar a aplicação com sistemas de terceiros, como instituições de caridade e serviços de pagamento, desde que permitam a recepção de doações via pix.

Os requisitos de design e experiência do usuário incluem uma interface simples, com foco no mapa e quantidade de doações, utilizando cores e figuras que transmitam uma sensação acolhedora.

Será desenvolvido um sistema de gerenciamento de usuários e autenticação, permitindo que as entidades cadastrem seus membros e garantindo autenticação para doadores, administradores da entidade e membros da entidade.

Será necessário armazenar dados pessoais dos usuários, como contato, nome e endereço. Medidas de proteção, como criptografia no banco de dados, serão implementadas, e os usuários poderão solicitar a exclusão de seus dados através do menu de sua conta.

O prazo estimado para o desenvolvimento da aplicação é de 6 meses. O projeto será realizado por uma equipe de voluntários, sem orçamento para desenvolvimento e manutenção."

**Founder**:
Usuário Discord: afonsocardz#9358

**A fazer**

- [x] Conceder o cargo "⚒┃Membro" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Revisar o Pull Request quando enviado, checando se está em conformes com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Lab no Discord, configurar as permissões dos cargos conforme os demais cargos de projetos;
- [x] Criar o canal do projeto (**NÃO** clone um dos canais existentes. Prefira criar um do zero, porém mantendo o mesmo padrão na nomenclatura);
- [x] Ajustar as permissões do canal do projeto, de acordo com o cargo criado para o projeto, usando como referência qualquer um dos demais canais dos demais projetos.

**Comment by dansenpir** [comment]
@salviotonon, consegue atuar nessa task?

**Comment by salviotonon** [comment]
@dansenpir, sim pode deixar essa pra min

**Comment by salviotonon** [comment]
@dansenpir  processo de recrutamento para o projeto em andamento.

**Comment by dansenpir** [comment]
@salviotonon
Os canais de Weekly e de comunicação (caso tenha sido optado), foram criados após o recrutamento do mínimo de membros de cada área?

**Comment by salviotonon** [comment]
@dansenpir 

não, foram abertos durante o processo de comunicação com o founder. atualmente o projeto esta em fase de recrutamento,warmy optou por criar o chat do projeto

**Comment by dansenpir** [comment]
Fluxo finalizado.
